FROM bioconductor/bioconductor_docker:devel

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends openssh-server r-bioc-biobase \
    && cp -a /usr/lib/R/site-library/BiocGenerics /usr/local/lib/R/site-library/ \
    && cp -a /usr/lib/R/site-library/Biobase /usr/local/lib/R/site-library/ \
    && mkdir -p /var/run/sshd /etc/ssh/sshd_config.d \
    && printf '%s\n' \
        'PasswordAuthentication yes' \
        'PermitRootLogin no' \
        'AllowUsers rstudio' \
        'AllowTcpForwarding yes' \
        'AllowStreamLocalForwarding yes' \
        > /etc/ssh/sshd_config.d/positron.conf \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/rstudio

COPY --chown=rstudio:rstudio . /home/rstudio/

RUN Rscript -e "options(repos = c(CRAN = 'https://cran.r-project.org')); devtools::install('.', dependencies=FALSE, build_vignettes=TRUE, upgrade=FALSE)"

EXPOSE 22

CMD ["/bin/bash", "-lc", "set -euo pipefail; : \"${PASSWORD:?Set PASSWORD to enable SSH login}\"; echo \"rstudio:${PASSWORD}\" | chpasswd; ssh-keygen -A >/dev/null 2>&1; exec /usr/sbin/sshd -D -e"]
