---
title: "How to Create a Workshop Package"
subtitle: "(Automatically)"
author: Sean Davis^[seandavi@gmail.com]
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to create a workshop package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Quickstart

- [ ] Clone this repo (not fork)
- [ ] Edit `DESCRIPTION` file
  - [ ] Change package name
  - [ ] Change title and description
  - [ ] Change authors
  - [ ] Check dependencies
  - [ ] Change DockerImage tag
- [ ] Edit `.github/workflows/basic_checks.yaml`
- [ ] Write a normal R package that can be installed
- [ ] Include one or more vignettes that will constitute the workshop materials

## Details

### Clone this repo

```
git clone https://github.com/seandavi/BuildABiocWorkshop2020 MYPKGDIR
```

### Edit `DESCRIPTION` file

- Change the package name to something identifiable and descriptive, ideally 
something that will be somewhat unique. 
- Edit the title and description as per any normal R package.
- Update authors (unless you want me to get credit for your work).
- Workshop packages are normal R packages, so dependencies work as usual. If
you are going to depend on something on github, be sure to specify the correct
repo `username/reponame`. Installation will deal with this.

### Edit `.github/workflows/basic_checks.yaml`


### Add "secrets" to github repo
 
- required secrets and their names

- `DOCKER_USERNAME`
- `DOCKER_PASSWORD`
- `


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

